---
classes:
  - exercises:
      - file: "../exercises/00-getting-started/README.md"
        title: "Getting Started"
        syntax: "md"
      - file: "../exercises/01-explore-console/README.md"
        title: "Explore the CAST AI Console"
        syntax: "md"
      - file: "../exercises/02-connect-cluster/README.md"
        title: "Connect Your Cluster"
        syntax: "md"
      - file: "../exercises/03-deploy-demo/README.md"
        title: "Deploy Demo Application"
        syntax: "md"
      - file: "../exercises/04-enable-vpa/README.md"
        title: "Enable VPA"
        syntax: "md"
      - file: "../exercises/05-binpacking/README.md"
        title: "Bin Packing"
        syntax: "md"
      - file: "../exercises/06-enable-node-autoscaler/README.md"
        title: "Enable Node Autoscaler"
        syntax: "md"
      - file: "../exercises/07-rebalance/README.md"
        title: "Rebalance"
        syntax: "md"
      - file: "../exercises/08-hibernation/README.md"
        title: "Hibernation"
        syntax: "md"
      - file: "../exercises/09-closing/README.md"
        title: "Closing"
        syntax: "md"
